# Generated by Django 4.1.2 on 2022-11-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_update_at_message_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='chat.room', verbose_name='Чат'),
            preserve_default=False,
        ),
    ]
