# Generated by Django 4.1.2 on 2022-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.CharField(default=' ', max_length=255, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
